name: Release Package

on:
 push:
  branches:
   - main

jobs:
 release:
  name: Release
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Setup Bun
     uses: oven-sh/setup-bun@v1
     with:
      bun-version: latest

   - name: Install dependencies
     run: bun install

   - name: Build package
     run: bun run build

   - name: Publish to NPM
     env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
     run: |
      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      bun publish
