name: Release Package

on:
 workflow_call:
  secrets:
   NPM_TOKEN:
    required: true
   GITHUB_TOKEN:
    required: true

permissions:
 contents: read
 packages: write

jobs:
 release:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Bun
     uses: oven-sh/setup-bun@v2
     with:
      bun-version: 'latest'

   - name: Configure npm for GitHub Packages
     env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: |
      npm config set '//npm.pkg.github.com/:_authToken' "${{ secrets.GITHUB_TOKEN }}"

   - name: Install dependencies
     run: bun install

   - name: Build the package (if applicable)
     run: bun run build

   - name: Publish to GitHub Packages
     env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: |
      npm publish --registry https://npm.pkg.github.com/

   - name: Configure npm for npm Registry
     env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
     run: |
      npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

   - name: Publish to npm Registry
     env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
     run: |
      npm publish --registry https://registry.npmjs.org/
