name: Release Package

on:
 push:
  branches:
   - main

jobs:
 release:
  name: Release
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Bun
     uses: oven-sh/setup-bun@v2
     with:
      bun-version: latest

   - name: Configure .npmrc for GitHub Packages
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: |
      echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc

   - name: Publish to GitHub Packages
     run: |
      npm publish --registry=https://npm.pkg.github.com/

   - name: Configure .npmrc for npm Registry
     env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
     run: |
      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

   - name: Publish to npm Registry
     run: |
      npm publish --registry=https://registry.npmjs.org/
