name: Release Package

on:
 push:
  branches:
   - main

jobs:
 release:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write
   id-token: write

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node
     uses: actions/setup-node@v4
     with:
      node-version: '20.x'
      registry-url: 'https://registry.npmjs.org'

   - name: Setup Bun
     uses: oven-sh/setup-bun@v2
     with:
      bun-version: 'latest'

   - name: Install dependencies
     run: bun install

   - name: Log into NPM
     run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
     env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

   - name: Log the NPM_TOKEN value again
     run: echo $TEST
     env:
      TEST: ${{ secrets.TEST }}

   - name: Publish to GitHub Packages
     run: npm publish
     env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
