name: Release Package

on:
 push:
  branches:
   - main

permissions:
 contents: read
 packages: write

jobs:
 release:
  uses: rubriclab/package/.github/workflows/release-package.yml@main
  secrets:
   GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
