name: Release Package

on:
 push:
  branches:
   - main

jobs:
 release:
  uses: rubriclab/package/.github/workflows/release-package.yml@main
  secrets:
   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
